from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager
import datetime
import random
class CustomAccountManager(BaseUserManager):
    def create_superuser(self, email, user_name, first_name, password, **other_fields):
        other_fields.setdefault('is_staff', True)
        other_fields.setdefault('is_superuser', True)
        other_fields.setdefault('is_active', True)

        if other_fields.get('is_staff') is not True:
            raise ValueError(
                'Superuser must be assigned to is_staff=True.')
        if other_fields.get('is_superuser') is not True:
            raise ValueError(
                'Superuser must be assigned to is_superuser=True.')

        return self.create_user(email, user_name, first_name, password, **other_fields)

    def create_user(self, email, user_name, first_name, password, **other_fields):

        if not email:
            raise ValueError(_('You must provide an email address'))

        email = self.normalize_email(email)
        user = self.model(email=email, user_name=user_name,
                          first_name=first_name, **other_fields)
        user.set_password(password)
        user.save()
        return user
class NewUser(AbstractBaseUser, PermissionsMixin):
    empid=models.AutoField(primary_key=True)
    email = models.EmailField(_('email address'), unique=True)
    user_name = models.CharField(max_length=50, unique=True)
    first_name = models.CharField(max_length=80, blank=True)
    Address = models.CharField(_(
        'address'), max_length=300, blank=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    objects = CustomAccountManager()
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['user_name', 'first_name']
    
    def __int__(self):
        return self.id
class InputConfiguration(models.Model):
    sr_no=models.AutoField(primary_key=True)
    desc=models.CharField(max_length=500)
    ft_hardware=models.FloatField()
    active=models.FloatField()
    passive=models.FloatField()
    ddcsensor=models.FloatField()
    thirdparty=models.FloatField()
    cabpiptray=models.FloatField()
    ft_hardware1=models.FloatField()
    active1=models.FloatField()
    passive1=models.FloatField()
    ddcsensor1=models.FloatField()
    thirdparty1=models.FloatField()
    cabpiptray1=models.FloatField()
    ftmandayeffort=models.FloatField()
    othersmicffort=models.FloatField()
    ft2=models.FloatField()
    ft3=models.FloatField()
    ft4=models.FloatField()



class vpss(models.Model):
    sr_no=models.AutoField(primary_key=True)
    MakeBrand=models.CharField(max_length=500)
    Model=models.CharField(max_length=500)
    InstallationEquipments=models.CharField(max_length=500)
    UnitDescription=models.CharField(max_length=500)
    Qty=models.IntegerField()
    InputPrice =models.IntegerField()
    Discount=models.IntegerField()
    DiscountedPrice=models.IntegerField()
    Freight=models.IntegerField()
    InputCostInclusiveoffreight=models.IntegerField()
    InterestCOM=models.IntegerField()
    UnitCost=models.IntegerField()
    InwardTax=models.IntegerField()
    UnitCostInclusiveofRisk=models.IntegerField()
    ContigencyPercentage=models.IntegerField()
    UnitCostInclusiveofContigency=models.IntegerField()
    TotalCost=models.IntegerField()
    Margin=models.IntegerField()
    Unit_Price=models.IntegerField()
    TotalPrice=models.IntegerField()
    WarrantyCharges=models.IntegerField()
    UnitPrice=models.IntegerField()
    FinalTotalPrice=models.IntegerField()
    InsuranceCharges =models.IntegerField()
    ListPricewithoutRoundup =models.IntegerField()
    ListPricewithRoundedup =models.IntegerField()
    
class SpazioPriceCalculator(models.Model):
    sr_no=models.AutoField(primary_key=True)
    Components=models.CharField(max_length=150)
    Quantity=models.IntegerField()
    Rate=models.IntegerField(default=0)
    SubTotal=models.IntegerField(default=0)
    Warranty=models.IntegerField(default=0)
    TotalwithWarranty=models.IntegerField(default=0)
    COM=models.IntegerField(default=0)
    TotalAmountwithInsurance=models.IntegerField(default=0)
    Year2=models.IntegerField(default=0)
    Year3=models.IntegerField(default=0)
    Total=models.IntegerField(default=0)
    
class HardWareGeneral(models.Model):
    sr_no=models.AutoField(primary_key=True)
    MakeBrand=models.CharField(max_length=500)
    Model=models.CharField(max_length=500)
    InstallationEquipments=models.CharField(max_length=500)
    UnitDescription=models.CharField(max_length=500)
    Qty=models.IntegerField()
    InputPrice =models.IntegerField()
    Discount=models.IntegerField()
    DiscountedPrice=models.IntegerField()
    Freight=models.IntegerField()
    InputCostInclusiveoffreight=models.IntegerField()
    InterestCOM=models.IntegerField()
    UnitCost=models.IntegerField()
    InwardTax=models.IntegerField()
    UnitCostInclusiveofRisk=models.IntegerField()
    ContigencyPercentage=models.IntegerField()
    UnitCostInclusiveofContigency=models.IntegerField()
    
    Margin=models.IntegerField()
    Unit_Price=models.IntegerField()
    
    WarrantyCharges=models.IntegerField()
    UnitPrice=models.IntegerField()
    
    InsuranceCharges =models.IntegerField()
    ListPricewithoutRoundup =models.IntegerField()
    ListPricewithRoundedup =models.IntegerField()
class HardWareIpVariant(models.Model):
    sr_no=models.AutoField(primary_key=True)
    MakeBrand=models.CharField(max_length=500)
    Model=models.CharField(max_length=500)
    InstallationEquipments=models.CharField(max_length=500)
    UnitDescription=models.CharField(max_length=500)
    Qty=models.IntegerField()
    InputPrice =models.IntegerField()
    Discount=models.IntegerField()
    DiscountedPrice=models.IntegerField()
    Freight=models.IntegerField()
    InputCostInclusiveoffreight=models.IntegerField()
    InterestCOM=models.IntegerField()
    UnitCost=models.IntegerField()
    InwardTax=models.IntegerField()
    UnitCostInclusiveofRisk=models.IntegerField()
    ContigencyPercentage=models.IntegerField()
    UnitCostInclusiveofContigency=models.IntegerField()
    Margin=models.IntegerField()
    Unit_Price=models.IntegerField()    
    WarrantyCharges=models.IntegerField()
    UnitPrice=models.IntegerField()    
    InsuranceCharges =models.IntegerField()
    ListPricewithoutRoundup =models.IntegerField()
    ListPricewithRoundedup =models.IntegerField()
class HardWareActive(models.Model):
    sr_no=models.AutoField(primary_key=True)
    MakeBrand=models.CharField(max_length=500)
    Model=models.CharField(max_length=500)
    InstallationEquipments=models.CharField(max_length=500)
    UnitDescription=models.CharField(max_length=500)
    Qty=models.IntegerField()
    InputPrice =models.IntegerField()
    Discount=models.IntegerField()
    DiscountedPrice=models.IntegerField()
    Freight=models.IntegerField()
    InputCostInclusiveoffreight=models.IntegerField()
    InterestCOM=models.IntegerField()
    UnitCost=models.IntegerField()
    InwardTax=models.IntegerField()
    UnitCostInclusiveofRisk=models.IntegerField()
    ContigencyPercentage=models.IntegerField()
    UnitCostInclusiveofContigency=models.IntegerField()
    
    Margin=models.IntegerField()
    Unit_Price=models.IntegerField()
    
    WarrantyCharges=models.IntegerField()
    UnitPrice=models.IntegerField()
    
    InsuranceCharges =models.IntegerField()
    ListPricewithoutRoundup =models.IntegerField()
    ListPricewithRoundedup =models.IntegerField()
class HardWarePassive(models.Model):
    sr_no=models.AutoField(primary_key=True)
    MakeBrand=models.CharField(max_length=500)
    Model=models.CharField(max_length=500)
    InstallationEquipments=models.CharField(max_length=500)
    UnitDescription=models.CharField(max_length=500)
    Qty=models.IntegerField()
    InputPrice =models.IntegerField()
    Discount=models.IntegerField()
    DiscountedPrice=models.IntegerField()
    Freight=models.IntegerField()
    InputCostInclusiveoffreight=models.IntegerField()
    InterestCOM=models.IntegerField()
    UnitCost=models.IntegerField()
    InwardTax=models.IntegerField()
    UnitCostInclusiveofRisk=models.IntegerField()
    ContigencyPercentage=models.IntegerField()
    UnitCostInclusiveofContigency=models.IntegerField()
    
    Margin=models.IntegerField()
    Unit_Price=models.IntegerField()
    
    WarrantyCharges=models.IntegerField()
    UnitPrice=models.IntegerField()
    
    InsuranceCharges =models.IntegerField()
    ListPricewithoutRoundup =models.IntegerField()
    ListPricewithRoundedup =models.IntegerField()
class HardWareEthernet(models.Model):
    sr_no=models.AutoField(primary_key=True)
    MakeBrand=models.CharField(max_length=500)
    Model=models.CharField(max_length=500)
    InstallationEquipments=models.CharField(max_length=500)
    UnitDescription=models.CharField(max_length=500)
    Qty=models.IntegerField()
    InputPrice =models.IntegerField()
    Discount=models.IntegerField()
    DiscountedPrice=models.IntegerField()
    Freight=models.IntegerField()
    InputCostInclusiveoffreight=models.IntegerField()
    InterestCOM=models.IntegerField()
    UnitCost=models.IntegerField()
    InwardTax=models.IntegerField()
    UnitCostInclusiveofRisk=models.IntegerField()
    ContigencyPercentage=models.IntegerField()
    UnitCostInclusiveofContigency=models.IntegerField()
    
    Margin=models.IntegerField()
    Unit_Price=models.IntegerField()
    
    WarrantyCharges=models.IntegerField()
    UnitPrice=models.IntegerField()
    
    InsuranceCharges =models.IntegerField()
    ListPricewithoutRoundup =models.IntegerField()
    ListPricewithRoundedup =models.IntegerField()
class HardWareDdc(models.Model):
    sr_no=models.AutoField(primary_key=True)
    MakeBrand=models.CharField(max_length=500)
    Model=models.CharField(max_length=500)
    InstallationEquipments=models.CharField(max_length=500)
    UnitDescription=models.CharField(max_length=500)
    Qty=models.IntegerField()
    InputPrice =models.IntegerField()
    Discount=models.IntegerField()
    DiscountedPrice=models.IntegerField()
    Freight=models.IntegerField()
    InputCostInclusiveoffreight=models.IntegerField()
    InterestCOM=models.IntegerField()
    UnitCost=models.IntegerField()
    InwardTax=models.IntegerField()
    UnitCostInclusiveofRisk=models.IntegerField()
    ContigencyPercentage=models.IntegerField()
    UnitCostInclusiveofContigency=models.IntegerField()
    
    Margin=models.IntegerField()
    Unit_Price=models.IntegerField()
    
    WarrantyCharges=models.IntegerField()
    UnitPrice=models.IntegerField()
    
    InsuranceCharges =models.IntegerField()
    ListPricewithoutRoundup =models.IntegerField()
    ListPricewithRoundedup =models.IntegerField()
class HardWareBmsSensors(models.Model):
    sr_no=models.AutoField(primary_key=True)
    MakeBrand=models.CharField(max_length=500)
    Model=models.CharField(max_length=500)
    InstallationEquipments=models.CharField(max_length=500)
    UnitDescription=models.CharField(max_length=500)
    Qty=models.IntegerField()
    InputPrice =models.IntegerField()
    Discount=models.IntegerField()
    DiscountedPrice=models.IntegerField()
    Freight=models.IntegerField()
    InputCostInclusiveoffreight=models.IntegerField()
    InterestCOM=models.IntegerField()
    UnitCost=models.IntegerField()
    InwardTax=models.IntegerField()
    UnitCostInclusiveofRisk=models.IntegerField()
    ContigencyPercentage=models.IntegerField()
    UnitCostInclusiveofContigency=models.IntegerField()
    
    Margin=models.IntegerField()
    Unit_Price=models.IntegerField()
    
    WarrantyCharges=models.IntegerField()
    UnitPrice=models.IntegerField()
    
    InsuranceCharges =models.IntegerField()
    ListPricewithoutRoundup =models.IntegerField()
    ListPricewithRoundedup =models.IntegerField()
class HardWareThirdParty(models.Model):
    sr_no=models.AutoField(primary_key=True)
    MakeBrand=models.CharField(max_length=500)
    Model=models.CharField(max_length=500)
    InstallationEquipments=models.CharField(max_length=500)
    UnitDescription=models.CharField(max_length=500)
    Qty=models.IntegerField()
    InputPrice =models.IntegerField()
    Discount=models.IntegerField()
    DiscountedPrice=models.IntegerField()
    Freight=models.IntegerField()
    InputCostInclusiveoffreight=models.IntegerField()
    InterestCOM=models.IntegerField()
    UnitCost=models.IntegerField()
    InwardTax=models.IntegerField()
    UnitCostInclusiveofRisk=models.IntegerField()
    ContigencyPercentage=models.IntegerField()
    UnitCostInclusiveofContigency=models.IntegerField()
    
    Margin=models.IntegerField()
    Unit_Price=models.IntegerField()
    
    WarrantyCharges=models.IntegerField()
    UnitPrice=models.IntegerField()
    
    InsuranceCharges =models.IntegerField()
    ListPricewithoutRoundup =models.IntegerField()
    ListPricewithRoundedup =models.IntegerField()
class HardWareBmsScabling(models.Model):
    sr_no=models.AutoField(primary_key=True)
    MakeBrand=models.CharField(max_length=500)
    Model=models.CharField(max_length=500)
    InstallationEquipments=models.CharField(max_length=500)
    UnitDescription=models.CharField(max_length=500)
    Qty=models.IntegerField()
    InputPrice =models.IntegerField()
    Discount=models.IntegerField()
    DiscountedPrice=models.IntegerField()
    Freight=models.IntegerField()
    InputCostInclusiveoffreight=models.IntegerField()
    InterestCOM=models.IntegerField()
    UnitCost=models.IntegerField()
    InwardTax=models.IntegerField()
    UnitCostInclusiveofRisk=models.IntegerField()
    ContigencyPercentage=models.IntegerField()
    UnitCostInclusiveofContigency=models.IntegerField()
    
    Margin=models.IntegerField()
    Unit_Price=models.IntegerField()
    
    WarrantyCharges=models.IntegerField()
    UnitPrice=models.IntegerField()
    
    InsuranceCharges =models.IntegerField()
    ListPricewithoutRoundup =models.IntegerField()
    ListPricewithRoundedup =models.IntegerField()
class HardWarePiping(models.Model):
    sr_no=models.AutoField(primary_key=True)
    MakeBrand=models.CharField(max_length=500)
    Model=models.CharField(max_length=500)
    InstallationEquipments=models.CharField(max_length=500)
    UnitDescription=models.CharField(max_length=500)
    Qty=models.IntegerField()
    InputPrice =models.IntegerField()
    Discount=models.IntegerField()
    DiscountedPrice=models.IntegerField()
    Freight=models.IntegerField()
    InputCostInclusiveoffreight=models.IntegerField()
    InterestCOM=models.IntegerField()
    UnitCost=models.IntegerField()
    InwardTax=models.IntegerField()
    UnitCostInclusiveofRisk=models.IntegerField()
    ContigencyPercentage=models.IntegerField()
    UnitCostInclusiveofContigency=models.IntegerField()
    
    Margin=models.IntegerField()
    Unit_Price=models.IntegerField()
    
    WarrantyCharges=models.IntegerField()
    UnitPrice=models.IntegerField()
    
    InsuranceCharges =models.IntegerField()
    ListPricewithoutRoundup =models.IntegerField()
    ListPricewithRoundedup =models.IntegerField()
class HardWareTrays(models.Model):
    sr_no=models.AutoField(primary_key=True)
    MakeBrand=models.CharField(max_length=500)
    Model=models.CharField(max_length=500)
    InstallationEquipments=models.CharField(max_length=500)
    UnitDescription=models.CharField(max_length=500)
    Qty=models.IntegerField()
    InputPrice =models.IntegerField()
    Discount=models.IntegerField()
    DiscountedPrice=models.IntegerField()
    Freight=models.IntegerField()
    InputCostInclusiveoffreight=models.IntegerField()
    InterestCOM=models.IntegerField()
    UnitCost=models.IntegerField()
    InwardTax=models.IntegerField()
    UnitCostInclusiveofRisk=models.IntegerField()
    ContigencyPercentage=models.IntegerField()
    UnitCostInclusiveofContigency=models.IntegerField()
    
    Margin=models.IntegerField()
    Unit_Price=models.IntegerField()
    
    WarrantyCharges=models.IntegerField()
    UnitPrice=models.IntegerField()
    
    InsuranceCharges =models.IntegerField()
    ListPricewithoutRoundup =models.IntegerField()
    ListPricewithRoundedup =models.IntegerField()
class HardWareGeneralInstall(models.Model):
    sr_no=models.AutoField(primary_key=True)
    MakeBrand=models.CharField(max_length=500)
    Model=models.CharField(max_length=500)
    InstallationEquipments=models.CharField(max_length=500)
    UnitDescription=models.CharField(max_length=500)
    Qty=models.IntegerField()
    InputPrice =models.IntegerField()
    Discount=models.IntegerField()
    DiscountedPrice=models.IntegerField()
    Freight=models.IntegerField()
    InputCostInclusiveoffreight=models.IntegerField()
    InterestCOM=models.IntegerField()
    UnitCost=models.IntegerField()
    InwardTax=models.IntegerField()
    UnitCostInclusiveofRisk=models.IntegerField()
    ContigencyPercentage=models.IntegerField()
    UnitCostInclusiveofContigency=models.IntegerField()
    
    Margin=models.IntegerField()
    Unit_Price=models.IntegerField()
    
    WarrantyCharges=models.IntegerField()
    UnitPrice=models.IntegerField()
    
    InsuranceCharges =models.IntegerField()
    ListPricewithoutRoundup =models.IntegerField()
    ListPricewithRoundedup =models.IntegerField()
class HardWareIpVariantInstall(models.Model):
    sr_no=models.AutoField(primary_key=True)
    MakeBrand=models.CharField(max_length=500)
    Model=models.CharField(max_length=500)
    InstallationEquipments=models.CharField(max_length=500)
    UnitDescription=models.CharField(max_length=500)
    Qty=models.IntegerField()
    InputPrice =models.IntegerField()
    Discount=models.IntegerField()
    DiscountedPrice=models.IntegerField()
    Freight=models.IntegerField()
    InputCostInclusiveoffreight=models.IntegerField()
    InterestCOM=models.IntegerField()
    UnitCost=models.IntegerField()
    InwardTax=models.IntegerField()
    UnitCostInclusiveofRisk=models.IntegerField()
    ContigencyPercentage=models.IntegerField()
    UnitCostInclusiveofContigency=models.IntegerField()
    
    Margin=models.IntegerField()
    Unit_Price=models.IntegerField()
    
    WarrantyCharges=models.IntegerField()
    UnitPrice=models.IntegerField()
    
    InsuranceCharges =models.IntegerField()
    ListPricewithoutRoundup =models.IntegerField()
    ListPricewithRoundedup =models.IntegerField()
class HardWareActiveInstall(models.Model):
    sr_no=models.AutoField(primary_key=True)
    MakeBrand=models.CharField(max_length=500)
    Model=models.CharField(max_length=500)
    InstallationEquipments=models.CharField(max_length=500)
    UnitDescription=models.CharField(max_length=500)
    Qty=models.IntegerField()
    InputPrice =models.IntegerField()
    Discount=models.IntegerField()
    DiscountedPrice=models.IntegerField()
    Freight=models.IntegerField()
    InputCostInclusiveoffreight=models.IntegerField()
    InterestCOM=models.IntegerField()
    UnitCost=models.IntegerField()
    InwardTax=models.IntegerField()
    UnitCostInclusiveofRisk=models.IntegerField()
    ContigencyPercentage=models.IntegerField()
    UnitCostInclusiveofContigency=models.IntegerField()
    
    Margin=models.IntegerField()
    Unit_Price=models.IntegerField()
    
    WarrantyCharges=models.IntegerField()
    UnitPrice=models.IntegerField()
    
    InsuranceCharges =models.IntegerField()
    ListPricewithoutRoundup =models.IntegerField()
    ListPricewithRoundedup =models.IntegerField()
class HardWarePassiveInstall(models.Model):
    sr_no=models.AutoField(primary_key=True)
    MakeBrand=models.CharField(max_length=500)
    Model=models.CharField(max_length=500)
    InstallationEquipments=models.CharField(max_length=500)
    UnitDescription=models.CharField(max_length=500)
    Qty=models.IntegerField()
    InputPrice =models.IntegerField()
    Discount=models.IntegerField()
    DiscountedPrice=models.IntegerField()
    Freight=models.IntegerField()
    InputCostInclusiveoffreight=models.IntegerField()
    InterestCOM=models.IntegerField()
    UnitCost=models.IntegerField()
    InwardTax=models.IntegerField()
    UnitCostInclusiveofRisk=models.IntegerField()
    ContigencyPercentage=models.IntegerField()
    UnitCostInclusiveofContigency=models.IntegerField()
    
    Margin=models.IntegerField()
    Unit_Price=models.IntegerField()
    
    WarrantyCharges=models.IntegerField()
    UnitPrice=models.IntegerField()
    
    InsuranceCharges =models.IntegerField()
    ListPricewithoutRoundup =models.IntegerField()
    ListPricewithRoundedup =models.IntegerField()
class HardWareEthernetInstall(models.Model):
    sr_no=models.AutoField(primary_key=True)
    MakeBrand=models.CharField(max_length=500)
    Model=models.CharField(max_length=500)
    InstallationEquipments=models.CharField(max_length=500)
    UnitDescription=models.CharField(max_length=500)
    Qty=models.IntegerField()
    InputPrice =models.IntegerField()
    Discount=models.IntegerField()
    DiscountedPrice=models.IntegerField()
    Freight=models.IntegerField()
    InputCostInclusiveoffreight=models.IntegerField()
    InterestCOM=models.IntegerField()
    UnitCost=models.IntegerField()
    InwardTax=models.IntegerField()
    UnitCostInclusiveofRisk=models.IntegerField()
    ContigencyPercentage=models.IntegerField()
    UnitCostInclusiveofContigency=models.IntegerField()
    
    Margin=models.IntegerField()
    Unit_Price=models.IntegerField()
    
    WarrantyCharges=models.IntegerField()
    UnitPrice=models.IntegerField()
    
    InsuranceCharges =models.IntegerField()
    ListPricewithoutRoundup =models.IntegerField()
    ListPricewithRoundedup =models.IntegerField()
class HardWareDdcInstall(models.Model):
    sr_no=models.AutoField(primary_key=True)
    MakeBrand=models.CharField(max_length=500)
    Model=models.CharField(max_length=500)
    InstallationEquipments=models.CharField(max_length=500)
    UnitDescription=models.CharField(max_length=500)
    Qty=models.IntegerField()
    InputPrice =models.IntegerField()
    Discount=models.IntegerField()
    DiscountedPrice=models.IntegerField()
    Freight=models.IntegerField()
    InputCostInclusiveoffreight=models.IntegerField()
    InterestCOM=models.IntegerField()
    UnitCost=models.IntegerField()
    InwardTax=models.IntegerField()
    UnitCostInclusiveofRisk=models.IntegerField()
    ContigencyPercentage=models.IntegerField()
    UnitCostInclusiveofContigency=models.IntegerField()
    
    Margin=models.IntegerField()
    Unit_Price=models.IntegerField()
    
    WarrantyCharges=models.IntegerField()
    UnitPrice=models.IntegerField()
    
    InsuranceCharges =models.IntegerField()
    ListPricewithoutRoundup =models.IntegerField()
    ListPricewithRoundedup =models.IntegerField()
class HardWareBmsSensorsInstall(models.Model):
    sr_no=models.AutoField(primary_key=True)
    MakeBrand=models.CharField(max_length=500)
    Model=models.CharField(max_length=500)
    InstallationEquipments=models.CharField(max_length=500)
    UnitDescription=models.CharField(max_length=500)
    Qty=models.IntegerField()
    InputPrice =models.IntegerField()
    Discount=models.IntegerField()
    DiscountedPrice=models.IntegerField()
    Freight=models.IntegerField()
    InputCostInclusiveoffreight=models.IntegerField()
    InterestCOM=models.IntegerField()
    UnitCost=models.IntegerField()
    InwardTax=models.IntegerField()
    UnitCostInclusiveofRisk=models.IntegerField()
    ContigencyPercentage=models.IntegerField()
    UnitCostInclusiveofContigency=models.IntegerField()
    
    Margin=models.IntegerField()
    Unit_Price=models.IntegerField()
    
    WarrantyCharges=models.IntegerField()
    UnitPrice=models.IntegerField()
    
    InsuranceCharges =models.IntegerField()
    ListPricewithoutRoundup =models.IntegerField()
    ListPricewithRoundedup =models.IntegerField()
class HardWareThirdPartyInstall(models.Model):
    sr_no=models.AutoField(primary_key=True)
    MakeBrand=models.CharField(max_length=500)
    Model=models.CharField(max_length=500)
    InstallationEquipments=models.CharField(max_length=500)
    UnitDescription=models.CharField(max_length=500)
    Qty=models.IntegerField()
    InputPrice =models.IntegerField()
    Discount=models.IntegerField()
    DiscountedPrice=models.IntegerField()
    Freight=models.IntegerField()
    InputCostInclusiveoffreight=models.IntegerField()
    InterestCOM=models.IntegerField()
    UnitCost=models.IntegerField()
    InwardTax=models.IntegerField()
    UnitCostInclusiveofRisk=models.IntegerField()
    ContigencyPercentage=models.IntegerField()
    UnitCostInclusiveofContigency=models.IntegerField()
    
    Margin=models.IntegerField()
    Unit_Price=models.IntegerField()
    
    WarrantyCharges=models.IntegerField()
    UnitPrice=models.IntegerField()
    
    InsuranceCharges =models.IntegerField()
    ListPricewithoutRoundup =models.IntegerField()
    ListPricewithRoundedup =models.IntegerField()
class HardWareBmsScablingInstall(models.Model):
    sr_no=models.AutoField(primary_key=True)
    MakeBrand=models.CharField(max_length=500)
    Model=models.CharField(max_length=500)
    InstallationEquipments=models.CharField(max_length=500)
    UnitDescription=models.CharField(max_length=500)
    Qty=models.IntegerField()
    InputPrice =models.IntegerField()
    Discount=models.IntegerField()
    DiscountedPrice=models.IntegerField()
    Freight=models.IntegerField()
    InputCostInclusiveoffreight=models.IntegerField()
    InterestCOM=models.IntegerField()
    UnitCost=models.IntegerField()
    InwardTax=models.IntegerField()
    UnitCostInclusiveofRisk=models.IntegerField()
    ContigencyPercentage=models.IntegerField()
    UnitCostInclusiveofContigency=models.IntegerField()
    
    Margin=models.IntegerField()
    Unit_Price=models.IntegerField()
    
    WarrantyCharges=models.IntegerField()
    UnitPrice=models.IntegerField()
    
    InsuranceCharges =models.IntegerField()
    ListPricewithoutRoundup =models.IntegerField()
    ListPricewithRoundedup =models.IntegerField()
class HardWarePipingInstall(models.Model):
    sr_no=models.AutoField(primary_key=True)
    MakeBrand=models.CharField(max_length=500)
    Model=models.CharField(max_length=500)
    InstallationEquipments=models.CharField(max_length=500)
    UnitDescription=models.CharField(max_length=500)
    Qty=models.IntegerField()
    InputPrice =models.IntegerField()
    Discount=models.IntegerField()
    DiscountedPrice=models.IntegerField()
    Freight=models.IntegerField()
    InputCostInclusiveoffreight=models.IntegerField()
    InterestCOM=models.IntegerField()
    UnitCost=models.IntegerField()
    InwardTax=models.IntegerField()
    UnitCostInclusiveofRisk=models.IntegerField()
    ContigencyPercentage=models.IntegerField()
    UnitCostInclusiveofContigency=models.IntegerField()
    
    Margin=models.IntegerField()
    Unit_Price=models.IntegerField()
    
    WarrantyCharges=models.IntegerField()
    UnitPrice=models.IntegerField()
    
    InsuranceCharges =models.IntegerField()
    ListPricewithoutRoundup =models.IntegerField()
    ListPricewithRoundedup =models.IntegerField()
class HardWareTraysInstall(models.Model):
    sr_no=models.AutoField(primary_key=True)
    MakeBrand=models.CharField(max_length=500)
    Model=models.CharField(max_length=500)
    InstallationEquipments=models.CharField(max_length=500)
    UnitDescription=models.CharField(max_length=500)
    Qty=models.IntegerField()
    InputPrice =models.IntegerField()
    Discount=models.IntegerField()
    DiscountedPrice=models.IntegerField()
    Freight=models.IntegerField()
    InputCostInclusiveoffreight=models.IntegerField()
    InterestCOM=models.IntegerField()
    UnitCost=models.IntegerField()
    InwardTax=models.IntegerField()
    UnitCostInclusiveofRisk=models.IntegerField()
    ContigencyPercentage=models.IntegerField()
    UnitCostInclusiveofContigency=models.IntegerField()
    
    Margin=models.IntegerField()
    Unit_Price=models.IntegerField()
    
    WarrantyCharges=models.IntegerField()
    UnitPrice=models.IntegerField()
    
    InsuranceCharges =models.IntegerField()
    ListPricewithoutRoundup =models.IntegerField()
    ListPricewithRoundedup =models.IntegerField()
class ManEffortsInstall(models.Model):
    sr_no=models.AutoField(primary_key=True)
    MakeBrand=models.CharField(max_length=500)
    Model=models.CharField(max_length=500)
    InstallationEquipments=models.CharField(max_length=500)
    UnitDescription=models.CharField(max_length=500)
    Qty=models.IntegerField()
    InputPrice =models.IntegerField()
    Discount=models.IntegerField()
    DiscountedPrice=models.IntegerField()
    Freight=models.IntegerField()
    InputCostInclusiveoffreight=models.IntegerField()
    InterestCOM=models.IntegerField()
    UnitCost=models.IntegerField()
    InwardTax=models.IntegerField()
    UnitCostInclusiveofRisk=models.IntegerField()
    ContigencyPercentage=models.IntegerField()
    UnitCostInclusiveofContigency=models.IntegerField()
    
    Margin=models.IntegerField()
    Unit_Price=models.IntegerField()
    
    WarrantyCharges=models.IntegerField()
    UnitPrice=models.IntegerField()
    
    InsuranceCharges =models.IntegerField()
    ListPricewithoutRoundup =models.IntegerField()
    ListPricewithRoundedup =models.IntegerField()
class Desk_Booking_Solution(models.Model):
    sr_no=models.AutoField(primary_key=True)
    Packs_Slabs=models.CharField(max_length=15)
    Max_Slab=models.IntegerField() 
    Rate=models.IntegerField()
    Total_Quantity=models.IntegerField()
    Volume=models.IntegerField()
    Rate_Per_Slab =models.IntegerField()
    Total=models.IntegerField()
class Desk_Utilization_Solution(models.Model):
    sr_no=models.AutoField(primary_key=True)
    Packs_Slabs=models.CharField(max_length=15)
    Max_Slab=models.IntegerField() 
    Rate=models.IntegerField()
    Total_Quantity=models.IntegerField()
    Volume=models.IntegerField()
    Rate_Per_Slab =models.IntegerField()
    Total=models.IntegerField()
class Desk_Planning_Solution(models.Model):
    sr_no=models.AutoField(primary_key=True)
    Packs_Slabs=models.CharField(max_length=15)
    Max_Slab=models.IntegerField() 
    Rate=models.IntegerField()
    Total_Quantity=models.IntegerField()
    Volume=models.IntegerField()
    Rate_Per_Slab =models.IntegerField()
    Total=models.IntegerField()
class Employee_One_Mobile_App(models.Model):
    sr_no=models.AutoField(primary_key=True)
    Packs_Slabs=models.CharField(max_length=15)
    Max_Slab=models.IntegerField() 
    Rate=models.IntegerField()
    Total_Quantity=models.IntegerField()
    Volume=models.IntegerField()
    Rate_Per_Slab =models.IntegerField()
    Total=models.IntegerField()
class Rostering(models.Model):
    sr_no=models.AutoField(primary_key=True)
    Packs_Slabs=models.CharField(max_length=15)
    Max_Slab=models.IntegerField() 
    Rate=models.IntegerField()
    Total_Quantity=models.IntegerField()
    Volume=models.IntegerField()
    Rate_Per_Slab =models.IntegerField()
    Total=models.IntegerField()
class Wayfinding(models.Model):
    sr_no=models.AutoField(primary_key=True)
    Packs_Slabs=models.CharField(max_length=15)
    Max_Slab=models.IntegerField() 
    Rate=models.IntegerField()
    Total_Quantity=models.IntegerField()
    Volume=models.IntegerField()
    Rate_Per_Slab =models.IntegerField()
    Total=models.IntegerField()
class Feedback(models.Model):
    sr_no=models.AutoField(primary_key=True)
    Packs_Slabs=models.CharField(max_length=15)
    Max_Slab=models.IntegerField() 
    Rate=models.IntegerField()
    Total_Quantity=models.IntegerField()
    Volume=models.IntegerField()
    Rate_Per_Slab =models.IntegerField()
    Total=models.IntegerField()
class Kiosk_License(models.Model):
    sr_no=models.AutoField(primary_key=True)
    Packs_Slabs=models.CharField(max_length=15)
    Max_Slab=models.IntegerField() 
    Rate=models.IntegerField()
    Total_Quantity=models.IntegerField()
    Volume=models.IntegerField()
    Rate_Per_Slab =models.IntegerField()
    Total=models.IntegerField()
class Meeting_Room_License_Occupancy(models.Model):
    sr_no=models.AutoField(primary_key=True)
    Packs_Slabs=models.CharField(max_length=15)
    Max_Slab=models.IntegerField() 
    Rate=models.IntegerField()
    Total_Quantity=models.IntegerField()
    Volume=models.IntegerField()
    Rate_Per_Slab =models.IntegerField()
    Total=models.IntegerField()
class Meeting_Room_License_People_Count(models.Model):
    sr_no=models.AutoField(primary_key=True)
    Packs_Slabs=models.CharField(max_length=15)
    Max_Slab=models.IntegerField() 
    Rate=models.IntegerField()
    Total_Quantity=models.IntegerField()
    Volume=models.IntegerField()
    Rate_Per_Slab =models.IntegerField()
    Total=models.IntegerField()
class Meeting_Room_License_Booking(models.Model):
    sr_no=models.AutoField(primary_key=True)
    Packs_Slabs=models.CharField(max_length=15)
    Max_Slab=models.IntegerField() 
    Rate=models.IntegerField()
    Total_Quantity=models.IntegerField()
    Volume=models.IntegerField()
    Rate_Per_Slab =models.IntegerField()
    Total=models.IntegerField()
class Restroom_License_People_Count(models.Model):
    sr_no=models.AutoField(primary_key=True)
    Packs_Slabs=models.CharField(max_length=15)
    Max_Slab=models.IntegerField() 
    Rate=models.IntegerField()
    Total_Quantity=models.IntegerField()
    Volume=models.IntegerField()
    Rate_Per_Slab =models.IntegerField()
    Total=models.IntegerField()
class Restroom_License_Wet_floor_detection(models.Model):
    sr_no=models.AutoField(primary_key=True)
    Packs_Slabs=models.CharField(max_length=15)
    Max_Slab=models.IntegerField() 
    Rate=models.IntegerField()
    Total_Quantity=models.IntegerField()
    Volume=models.IntegerField()
    Rate_Per_Slab =models.IntegerField()
    Total=models.IntegerField()
class Restroom_License_Odour(models.Model):
    sr_no=models.AutoField(primary_key=True)
    Packs_Slabs=models.CharField(max_length=15)
    Max_Slab=models.IntegerField() 
    Rate=models.IntegerField()
    Total_Quantity=models.IntegerField()
    Volume=models.IntegerField()
    Rate_Per_Slab =models.IntegerField()
    Total=models.IntegerField()
class Human_body_temperature_License(models.Model):
    sr_no=models.AutoField(primary_key=True)
    Packs_Slabs=models.CharField(max_length=15)
    Max_Slab=models.IntegerField() 
    Rate=models.IntegerField()
    Total_Quantity=models.IntegerField()
    Volume=models.IntegerField()
    Rate_Per_Slab =models.IntegerField()
    Total=models.IntegerField()
class Automate_Pricing(models.Model):
    sr_no=models.AutoField(primary_key=True)
    Model_No=models.CharField(max_length=50)
    Max_Slab=models.IntegerField()
    Pack_Desc=models.CharField(max_length=50)
    Inr_Basic=models.IntegerField()
    Inr_Basic_Per_Kpi=models.IntegerField()
    Inr_Premium=models.IntegerField()
    Inr_Premium_Per_Kpi=models.IntegerField()
    Usd_Basic=models.IntegerField()
    Usd_Premium=models.IntegerField()
class Software_Revised_Extra(models.Model):
    sr_no=models.AutoField(primary_key=True)
    Key=models.CharField(max_length=100)
    Value=models.FloatField()
    Info=models.CharField(max_length=100,blank=True)
    
class IandC(models.Model):
    sr_no=models.AutoField(primary_key=True)
    Deployment_Activity=models.CharField(max_length=300)
    Resource_Level=models.CharField(max_length=100)
    Common=models.IntegerField(default=0)
    Spazio_Software=models.IntegerField(default=0)
    Meeting_Room_Booking=models.IntegerField(default=0)
    Meeting_Room_People_count_occupancy=models.IntegerField(default=0)
    Restroom_Hygiene=models.IntegerField(default=0)
    IAQ_Automate=models.IntegerField(default=0)
    Wayfinding=models.IntegerField(default=0)
    Feedback=models.IntegerField(default=0)
    
class Summary(models.Model):
    sr_no=models.AutoField(primary_key=True)
    Level_of_Engineer=models.CharField(max_length=100)
    Common=models.IntegerField(default=0)
    Spazio_Software=models.IntegerField(default=0)
    Meeting_Room_Booking=models.IntegerField(default=0)
    Meeting_Room_People_count= models.IntegerField(default=0)
    Meeting_Room_People_count2=models.IntegerField(default=0)
    IAQ_Automate=models.IntegerField(default=0)
    Wayfinding=models.IntegerField(default=0)
    Feedback=models.IntegerField(default=0)
    Total_Man_Days=models.IntegerField(default=0)
    
class Efforts_Charges_for_Deployment(models.Model):
    sr_no=models.AutoField(primary_key=True)
    Level_of_Engineer=models.CharField(max_length=100)
    Per_Day_Rate=models.IntegerField(default=0)
    Per_Hour=models.FloatField(default=0)
    Rounded_Per_Hour_Rates=models.IntegerField(default=0)
    Total_Man_Days=models.IntegerField(default=0)
    Total_Man_Hours=models.IntegerField(default=0)
    
class Project_Management_Charges(models.Model):
    sr_no=models.AutoField(primary_key=True)
    Installation_Min=models.IntegerField(default=0)
    Installation_Max=models.IntegerField(default=0)
    PM_Percentage=models.IntegerField(default=0)
    
class PM_Mapping_table_After_Margin_column(models.Model):
    sr_no=models.AutoField(primary_key=True)
    Installation_Min=models.IntegerField(default=0)
    Installation_Max=models.IntegerField(default=0)
    PM_Percentage=models.IntegerField(default=0)
    
class PM_Mapping_table_After_Cost_column(models.Model):
    sr_no=models.AutoField(primary_key=True)
    Installation_Min=models.IntegerField(default=0)
    Installation_Max=models.IntegerField(default=0)
    PM_Percentage=models.IntegerField(default=0)
    
# class detailed_boq_general(models.Model):
#     sr_no=models.AutoField(primary_key=True)
#     Make=models.CharField(max_length=100)
#     Model=models.CharField(max_length=100)
#     Hardware_Items=models.CharField(max_length=100)
#     Qty=models.IntegerField(default=0)
#     Uom=models.CharField(max_length=100)
#     Cost_Supply_Rate=models.IntegerField(default=0)
#     Cost_Supply_Total=models.IntegerField(default=0)
#     Cost_Installation_Rate=models.IntegerField(default=0)
#     Cost_Installation_Total=models.IntegerField(default=0)
#     MRS_Rate=models.IntegerField(default=0)
#     MRS_Total=models.IntegerField(default=0)
#     MRI_Rate=models.IntegerField(default=0)
#     MRI_Total=models.IntegerField(default=0)
#     Supply_Rate=models.IntegerField(default=0)
#     Supply_Total=models.IntegerField(default=0)
#     Installation_Rate=models.IntegerField(default=0)
#     Installation_Total=models.IntegerField(default=0)



    
    
    
    