from django.db import models
class General(models.Model):
    sr_no=models.AutoField(primary_key=True)
    Make=models.CharField(max_length=300,default=" ")
    Model=models.CharField(max_length=300,default=" ")
    Hardware_Items=models.CharField(max_length=300,default=" ")
    Qty=models.IntegerField(default=0)
    Uom=models.CharField(max_length=100,default=" Per Device")
    Cost_Supply_Rate=models.IntegerField(default=0)
    Cost_Supply_Total=models.IntegerField(default=0)
    Cost_Installation_Rate=models.IntegerField(default=0)
    Cost_Installation_Total=models.IntegerField(default=0)
    MRS_Rate=models.IntegerField(default=0)
    MRS_Total=models.IntegerField(default=0)
    MRI_Rate=models.IntegerField(default=0)
    MRI_Total=models.IntegerField(default=0)
    Supply_Rate=models.IntegerField(default=0)
    Supply_Total=models.IntegerField(default=0)
    Installation_Rate=models.IntegerField(default=0)
    Installation_Total=models.IntegerField(default=0)
    Remarks=models.CharField(max_length=300,default=" ")
    Minimum_Qty=models.IntegerField(default=0)
    Minimum_Installation=models.IntegerField(default=0)
class Active(models.Model):
    sr_no=models.AutoField(primary_key=True)
    Make=models.CharField(max_length=300,default=" ")
    Model=models.CharField(max_length=300,default=" ")
    Hardware_Items=models.CharField(max_length=300,default=" ")
    Qty=models.IntegerField(default=0)
    Uom=models.CharField(max_length=100,default=" Per Device")
    Cost_Supply_Rate=models.IntegerField(default=0)
    Cost_Supply_Total=models.IntegerField(default=0)
    Cost_Installation_Rate=models.IntegerField(default=0)
    Cost_Installation_Total=models.IntegerField(default=0)
    MRS_Rate=models.IntegerField(default=0)
    MRS_Total=models.IntegerField(default=0)
    MRI_Rate=models.IntegerField(default=0)
    MRI_Total=models.IntegerField(default=0)
    Supply_Rate=models.IntegerField(default=0)
    Supply_Total=models.IntegerField(default=0)
    Installation_Rate=models.IntegerField(default=0)
    Installation_Total=models.IntegerField(default=0)
class Fiber(models.Model):
    sr_no=models.AutoField(primary_key=True)
    Make=models.CharField(max_length=300,default=" ")
    Model=models.CharField(max_length=300,default=" ")
    Hardware_Items=models.CharField(max_length=300,default=" ")
    Qty=models.IntegerField(default=0)
    Uom=models.CharField(max_length=100,default=" Per Device")
    Cost_Supply_Rate=models.IntegerField(default=0)
    Cost_Supply_Total=models.IntegerField(default=0)
    Cost_Installation_Rate=models.IntegerField(default=0)
    Cost_Installation_Total=models.IntegerField(default=0)
    MRS_Rate=models.IntegerField(default=0)
    MRS_Total=models.IntegerField(default=0)
    MRI_Rate=models.IntegerField(default=0)
    MRI_Total=models.IntegerField(default=0)
    Supply_Rate=models.IntegerField(default=0)
    Supply_Total=models.IntegerField(default=0)
    Installation_Rate=models.IntegerField(default=0)
    Installation_Total=models.IntegerField(default=0)
class Ethernet(models.Model):
    sr_no=models.AutoField(primary_key=True)
    Make=models.CharField(max_length=300,default=" ")
    Model=models.CharField(max_length=300,default=" ")
    Hardware_Items=models.CharField(max_length=300,default=" ")
    Qty=models.IntegerField(default=0)
    Uom=models.CharField(max_length=100,default=" Per Device")
    Cost_Supply_Rate=models.IntegerField(default=0)
    Cost_Supply_Total=models.IntegerField(default=0)
    Cost_Installation_Rate=models.IntegerField(default=0)
    Cost_Installation_Total=models.IntegerField(default=0)
    MRS_Rate=models.IntegerField(default=0)
    MRS_Total=models.IntegerField(default=0)
    MRI_Rate=models.IntegerField(default=0)
    MRI_Total=models.IntegerField(default=0)
    Supply_Rate=models.IntegerField(default=0)
    Supply_Total=models.IntegerField(default=0)
    Installation_Rate=models.IntegerField(default=0)
    Installation_Total=models.IntegerField(default=0)
class Ddc(models.Model):
    sr_no=models.AutoField(primary_key=True)
    Make=models.CharField(max_length=300,default=" ")
    Model=models.CharField(max_length=300,default=" ")
    Hardware_Items=models.CharField(max_length=300,default=" ")
    Qty=models.IntegerField(default=0)
    Uom=models.CharField(max_length=100,default=" Per Device")
    Cost_Supply_Rate=models.IntegerField(default=0)
    Cost_Supply_Total=models.IntegerField(default=0)
    Cost_Installation_Rate=models.IntegerField(default=0)
    Cost_Installation_Total=models.IntegerField(default=0)
    MRS_Rate=models.IntegerField(default=0)
    MRS_Total=models.IntegerField(default=0)
    MRI_Rate=models.IntegerField(default=0)
    MRI_Total=models.IntegerField(default=0)
    Supply_Rate=models.IntegerField(default=0)
    Supply_Total=models.IntegerField(default=0)
    Installation_Rate=models.IntegerField(default=0)
    Installation_Total=models.IntegerField(default=0)
class Bms_Sensors(models.Model):
    sr_no=models.AutoField(primary_key=True)
    Make=models.CharField(max_length=300,default=" ")
    Model=models.CharField(max_length=300,default=" ")
    Hardware_Items=models.CharField(max_length=300,default=" ")
    Qty=models.IntegerField(default=0)
    Uom=models.CharField(max_length=100,default=" Per Device")
    Cost_Supply_Rate=models.IntegerField(default=0)
    Cost_Supply_Total=models.IntegerField(default=0)
    Cost_Installation_Rate=models.IntegerField(default=0)
    Cost_Installation_Total=models.IntegerField(default=0)
    MRS_Rate=models.IntegerField(default=0)
    MRS_Total=models.IntegerField(default=0)
    MRI_Rate=models.IntegerField(default=0)
    MRI_Total=models.IntegerField(default=0)
    Supply_Rate=models.IntegerField(default=0)
    Supply_Total=models.IntegerField(default=0)
    Installation_Rate=models.IntegerField(default=0)
    Installation_Total=models.IntegerField(default=0)
class Bms_Cabling(models.Model):
    sr_no=models.AutoField(primary_key=True)
    Make=models.CharField(max_length=300,default=" ")
    Model=models.CharField(max_length=300,default=" ")
    Hardware_Items=models.CharField(max_length=300,default=" ")
    Qty=models.IntegerField(default=0)
    Uom=models.CharField(max_length=100,default=" Per Device")
    Cost_Supply_Rate=models.IntegerField(default=0)
    Cost_Supply_Total=models.IntegerField(default=0)
    Cost_Installation_Rate=models.IntegerField(default=0)
    Cost_Installation_Total=models.IntegerField(default=0)
    MRS_Rate=models.IntegerField(default=0)
    MRS_Total=models.IntegerField(default=0)
    MRI_Rate=models.IntegerField(default=0)
    MRI_Total=models.IntegerField(default=0)
    Supply_Rate=models.IntegerField(default=0)
    Supply_Total=models.IntegerField(default=0)
    Installation_Rate=models.IntegerField(default=0)
    Installation_Total=models.IntegerField(default=0)
class Bms_Piping(models.Model):
    sr_no=models.AutoField(primary_key=True)
    Make=models.CharField(max_length=300,default=" ")
    Model=models.CharField(max_length=300,default=" ")
    Hardware_Items=models.CharField(max_length=300,default=" ")
    Qty=models.IntegerField(default=0)
    Uom=models.CharField(max_length=100,default=" Per Device")
    Cost_Supply_Rate=models.IntegerField(default=0)
    Cost_Supply_Total=models.IntegerField(default=0)
    Cost_Installation_Rate=models.IntegerField(default=0)
    Cost_Installation_Total=models.IntegerField(default=0)
    MRS_Rate=models.IntegerField(default=0)
    MRS_Total=models.IntegerField(default=0)
    MRI_Rate=models.IntegerField(default=0)
    MRI_Total=models.IntegerField(default=0)
    Supply_Rate=models.IntegerField(default=0)
    Supply_Total=models.IntegerField(default=0)
    Installation_Rate=models.IntegerField(default=0)
    Installation_Total=models.IntegerField(default=0)
class Bms_Trays(models.Model):
    sr_no=models.AutoField(primary_key=True)
    Make=models.CharField(max_length=300,default=" ")
    Model=models.CharField(max_length=300,default=" ")
    Hardware_Items=models.CharField(max_length=300,default=" ")
    Qty=models.IntegerField(default=0)
    Uom=models.CharField(max_length=100,default=" Per Device")
    Cost_Supply_Rate=models.IntegerField(default=0)
    Cost_Supply_Total=models.IntegerField(default=0)
    Cost_Installation_Rate=models.IntegerField(default=0)
    Cost_Installation_Total=models.IntegerField(default=0)
    MRS_Rate=models.IntegerField(default=0)
    MRS_Total=models.IntegerField(default=0)
    MRI_Rate=models.IntegerField(default=0)
    MRI_Total=models.IntegerField(default=0)
    Supply_Rate=models.IntegerField(default=0)
    Supply_Total=models.IntegerField(default=0)
    Installation_Rate=models.IntegerField(default=0)
    Installation_Total=models.IntegerField(default=0)
class Soft_Items(models.Model):
    sr_no=models.AutoField(primary_key=True)
    Make=models.CharField(max_length=300,default=" ")
    Model=models.CharField(max_length=300,default=" ")
    Hardware_Items=models.CharField(max_length=300,default=" ")
    Qty=models.IntegerField(default=0)
    Uom=models.CharField(max_length=100,default=" Per Device")
    Cost_Supply_Rate=models.IntegerField(default=0)
    Cost_Supply_Total=models.IntegerField(default=0)
    Cost_Installation_Rate=models.IntegerField(default=0)
    Cost_Installation_Total=models.IntegerField(default=0)
    MRS_Rate=models.IntegerField(default=0)
    MRS_Total=models.IntegerField(default=0)
    MRI_Rate=models.IntegerField(default=0)
    MRI_Total=models.IntegerField(default=0)
    Supply_Rate=models.IntegerField(default=0)
    Supply_Total=models.IntegerField(default=0)
    Installation_Rate=models.IntegerField(default=0)
    Installation_Total=models.IntegerField(default=0)
    
    
    
# sr_no
#     Make
#     Model
#     Hardware_Items
#     Qty
#     Uom
#     Cost_Supply_Rate
#     Cost_Supply_Total
#     Cost_Installation_Rate
#     Cost_Installation_Total
#     MRS_Rate
#     MRS_Total
#     MRI_Rate
#     MRI_Total
#     Supply_Rate
#     Supply_Total
#     Installation_Rate
#     Installation_Total
#     Remarks=models.CharFi
#     Minimum_Qty
#     Minimum_Installation