# Generated by Django 4.0.4 on 2022-06-15 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='active',
            name='Uom',
            field=models.CharField(default=' Per Device', max_length=100),
        ),
        migrations.AlterField(
            model_name='bms_cabling',
            name='Uom',
            field=models.CharField(default=' Per Device', max_length=100),
        ),
        migrations.AlterField(
            model_name='bms_piping',
            name='Uom',
            field=models.CharField(default=' Per Device', max_length=100),
        ),
        migrations.AlterField(
            model_name='bms_sensors',
            name='Uom',
            field=models.CharField(default=' Per Device', max_length=100),
        ),
        migrations.AlterField(
            model_name='bms_trays',
            name='Uom',
            field=models.CharField(default=' Per Device', max_length=100),
        ),
        migrations.AlterField(
            model_name='ddc',
            name='Uom',
            field=models.CharField(default=' Per Device', max_length=100),
        ),
        migrations.AlterField(
            model_name='ethernet',
            name='Uom',
            field=models.CharField(default=' Per Device', max_length=100),
        ),
        migrations.AlterField(
            model_name='fiber',
            name='Uom',
            field=models.CharField(default=' Per Device', max_length=100),
        ),
        migrations.AlterField(
            model_name='general',
            name='Uom',
            field=models.CharField(default=' Per Device', max_length=100),
        ),
        migrations.AlterField(
            model_name='soft_items',
            name='Uom',
            field=models.CharField(default=' Per Device', max_length=100),
        ),
    ]
