# Generated by Django 4.0.4 on 2022-09-27 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_others_third_party'),
    ]

    operations = [
        migrations.DeleteModel(
            name='General',
        ),
    ]
