# Generated by Django 4.0.4 on 2022-07-22 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManEffortsInstall',
            fields=[
                ('sr_no', models.AutoField(primary_key=True, serialize=False)),
                ('MakeBrand', models.CharField(max_length=500)),
                ('Model', models.CharField(max_length=500)),
                ('InstallationEquipments', models.CharField(max_length=500)),
                ('UnitDescription', models.CharField(max_length=500)),
                ('Qty', models.IntegerField()),
                ('InputPrice', models.IntegerField()),
                ('Discount', models.IntegerField()),
                ('DiscountedPrice', models.IntegerField()),
                ('Freight', models.IntegerField()),
                ('InputCostInclusiveoffreight', models.IntegerField()),
                ('InterestCOM', models.IntegerField()),
                ('UnitCost', models.IntegerField()),
                ('InwardTax', models.IntegerField()),
                ('UnitCostInclusiveofRisk', models.IntegerField()),
                ('ContigencyPercentage', models.IntegerField()),
                ('UnitCostInclusiveofContigency', models.IntegerField()),
                ('Margin', models.IntegerField()),
                ('Unit_Price', models.IntegerField()),
                ('WarrantyCharges', models.IntegerField()),
                ('UnitPrice', models.IntegerField()),
                ('InsuranceCharges', models.IntegerField()),
                ('ListPricewithoutRoundup', models.IntegerField()),
                ('ListPricewithRoundedup', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='efforts_charges_for_deployment',
            name='Level_of_Engineer',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='efforts_charges_for_deployment',
            name='Per_Hour',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='summary',
            name='Level_of_Engineer',
            field=models.CharField(max_length=100),
        ),
    ]
