# Generated by Django 4.0.4 on 2022-09-29 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quotation',
        ),
    ]
