# Generated by Django 4.0.4 on 2022-09-29 07:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin1', '0002_delete_quotation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('ref_no', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('pdf', models.FileField(blank=True, upload_to='pdfs/')),
                ('excel', models.FileField(upload_to='excels/')),
                ('date', models.DateField(default=datetime.date(2022, 9, 29))),
                ('company_name', models.CharField(max_length=100)),
                ('input_data', models.TextField(max_length=500)),
                ('user_name', models.CharField(max_length=50)),
                ('emp_name', models.CharField(max_length=50)),
                ('_Trays2', models.CharField(default='', max_length=200)),
                ('_Bms_Trays', models.CharField(default='', max_length=200)),
                ('_Bms_Piping', models.CharField(default='', max_length=200)),
                ('_Bms_Cabling', models.CharField(default='', max_length=200)),
                ('_Bms_Sensors', models.CharField(default='', max_length=200)),
                ('_Ddc', models.CharField(default='', max_length=200)),
                ('_Ethernet', models.CharField(default='', max_length=200)),
                ('_Fiber', models.CharField(default='', max_length=200)),
                ('_Active', models.CharField(default='', max_length=200)),
                ('_Efforts', models.CharField(default='', max_length=200)),
                ('_Others', models.CharField(default='', max_length=200)),
                ('_hard', models.CharField(default='', max_length=200)),
                ('_Third_Party', models.CharField(default='', max_length=200)),
                ('description', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
