# Generated by Django 3.2.13 on 2022-04-23 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin1', '0002_auto_20220416_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.IntegerField()),
                ('desc', models.CharField(max_length=500)),
                ('ft_hardware', models.IntegerField()),
                ('active', models.IntegerField()),
                ('passive', models.IntegerField()),
                ('ddcsensor', models.IntegerField()),
                ('thirdparty', models.IntegerField()),
                ('cabpiptray', models.IntegerField()),
                ('ft_hardware1', models.IntegerField()),
                ('active1', models.IntegerField()),
                ('passive1', models.IntegerField()),
                ('ddcsensor1', models.IntegerField()),
                ('thirdparty1', models.IntegerField()),
                ('cabpiptray1', models.IntegerField()),
                ('ftmandayeffort', models.IntegerField()),
                ('othersmicffort', models.IntegerField()),
                ('ft2', models.IntegerField()),
                ('ft3', models.IntegerField()),
                ('ft4', models.IntegerField()),
            ],
        ),
    ]
