# Generated by Django 4.0.4 on 2022-08-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin1', '0002_maneffortsinstall_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='margin',
            fields=[
                ('sr_no', models.AutoField(primary_key=True, serialize=False)),
                ('Details', models.CharField(max_length=100)),
                ('Total_Cost', models.IntegerField(default=0)),
                ('Pr_Wt_Mrgn', models.IntegerField(default=0)),
                ('Gross_Mrgn', models.IntegerField(default=0)),
                ('Gross_Mrgn_In_Prcnt', models.IntegerField(default=0)),
                ('Sell_Price', models.IntegerField(default=0)),
                ('Net_Price', models.IntegerField(default=0)),
                ('Profit_On_Nt_Mrgn', models.IntegerField(default=0)),
            ],
        ),
    ]
