# Generated by Django 4.0.4 on 2022-04-25 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin1', '0003_inputconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='vpss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.IntegerField()),
                ('MakeBrand', models.CharField(max_length=500)),
                ('InstallationEquipments', models.CharField(max_length=500)),
                ('UnitDescription', models.CharField(max_length=500)),
                ('Qty', models.IntegerField()),
                ('InputPrice', models.IntegerField()),
                ('Discount', models.IntegerField()),
                ('DiscountedPrice', models.IntegerField()),
                ('Freight', models.IntegerField()),
                ('InputCostInclusiveoffreight', models.IntegerField()),
                ('InterestCOM', models.IntegerField()),
                ('UnitCost', models.IntegerField()),
                ('InwardTax', models.IntegerField()),
                ('UnitCostInclusiveofRisk', models.IntegerField()),
                ('ContigencyPercentage', models.IntegerField()),
                ('UnitCostInclusiveofContigency', models.IntegerField()),
                ('TotalCost', models.IntegerField()),
                ('Margin', models.IntegerField()),
                ('TotalPrice', models.IntegerField()),
                ('WarrantyCharges', models.IntegerField()),
                ('UnitPrice', models.IntegerField()),
                ('FinalTotalPrice', models.IntegerField()),
                ('InsuranceCharges', models.IntegerField()),
                ('ListPricewithoutRoundup', models.IntegerField()),
                ('ListPricewithRoundedup', models.IntegerField()),
            ],
        ),
    ]
