# Generated by Django 4.0.4 on 2022-08-13 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin1', '0004_soft_items_db'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soft_items_db',
            name='sr_no',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
