# Generated by Django 4.0.4 on 2022-08-24 18:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin1', '0005_alter_soft_items_db_sr_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('ref_no', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('pdf', models.FileField(upload_to='pdfs/')),
                ('excel', models.FileField(upload_to='excels/')),
                ('date', models.DateField(default=datetime.date(2022, 8, 24))),
                ('company_name', models.CharField(max_length=100)),
                ('input_data', models.CharField(max_length=200)),
            ],
        ),
    ]
