# Generated by Django 3.2.13 on 2022-04-25 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin1', '0005_vpss_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpss',
            name='Model',
            field=models.CharField(default=90, max_length=500),
            preserve_default=False,
        ),
    ]
