# Generated by Django 4.0.4 on 2022-08-26 18:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin1', '0006_quotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='date',
            field=models.DateField(default=datetime.date(2022, 8, 26)),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='input_data',
            field=models.CharField(max_length=2000),
        ),
    ]
