# Generated by Django 4.0.4 on 2022-08-26 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin1', '0007_alter_quotation_date_alter_quotation_input_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='user_email',
            field=models.EmailField(default='anmol@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
