# Generated by Django 4.0.4 on 2022-05-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin1', '0008_remove_hardwareactive_finaltotalprice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpss',
            name='FinalTotalPrice',
            field=models.IntegerField(default=9000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vpss',
            name='TotalCost',
            field=models.IntegerField(default=9000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vpss',
            name='TotalPrice',
            field=models.IntegerField(default=9000),
            preserve_default=False,
        ),
    ]
