# Generated by Django 4.0.4 on 2022-08-27 06:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin1', '0008_quotation_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='contact_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quotation',
            name='contact_person',
            field=models.CharField(default='anmol dada', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotation',
            name='description',
            field=models.CharField(default=' nikhil chakka', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotation',
            name='email',
            field=models.EmailField(default='nikhil@land.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotation',
            name='location',
            field=models.CharField(default='budhwar peth', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quotation',
            name='date',
            field=models.DateField(default=datetime.date(2022, 8, 27)),
        ),
    ]
