# Generated by Django 4.0.4 on 2022-05-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin1', '0009_vpss_finaltotalprice_vpss_totalcost_vpss_totalprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpazioPriceCalculator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Components', models.IntegerField()),
                ('Quantity', models.IntegerField()),
                ('Rate', models.IntegerField()),
                ('SubTotal', models.IntegerField()),
                ('Warranty', models.IntegerField()),
                ('TotalwithWarranty', models.IntegerField()),
                ('COM', models.IntegerField()),
                ('TotalAmountwithInsurance', models.IntegerField()),
                ('Year2', models.IntegerField()),
                ('Year3', models.IntegerField()),
                ('Total', models.IntegerField()),
            ],
        ),
    ]
