# Generated by Django 4.0.4 on 2022-08-27 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin1', '0009_quotation_contact_number_quotation_contact_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='input_data',
            field=models.TextField(max_length=500),
        ),
    ]
