# Generated by Django 4.0.4 on 2022-08-27 19:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin1', '0010_alter_quotation_input_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='description',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='email',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='location',
        ),
        migrations.AlterField(
            model_name='quotation',
            name='date',
            field=models.DateField(default=datetime.date(2022, 8, 28)),
        ),
    ]
