# Generated by Django 4.0.4 on 2022-05-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin1', '0010_spaziopricecalculator'),
    ]

    operations = [
        migrations.AddField(
            model_name='spaziopricecalculator',
            name='sr_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
