# Generated by Django 4.0.4 on 2022-08-29 08:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin1', '0011_remove_quotation_contact_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='user_email',
        ),
        migrations.AddField(
            model_name='quotation',
            name='user_name',
            field=models.CharField(default='anmol_a1', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quotation',
            name='date',
            field=models.DateField(default=datetime.date(2022, 8, 29)),
        ),
    ]
