# Generated by Django 4.0.4 on 2022-05-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin1', '0011_spaziopricecalculator_sr_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spaziopricecalculator',
            name='Components',
            field=models.CharField(max_length=150),
        ),
    ]
