# Generated by Django 4.0.4 on 2022-08-29 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin1', '0012_remove_quotation_user_email_quotation_user_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='emp_name',
            field=models.CharField(default='toshiba', max_length=50),
            preserve_default=False,
        ),
    ]
