# Generated by Django 4.0.4 on 2022-05-31 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin1', '0012_alter_spaziopricecalculator_components'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desk_Booking_Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Packs_Slabs', models.CharField(max_length=15)),
                ('Max_Slab', models.IntegerField()),
                ('Rate', models.IntegerField()),
                ('Total_Quantity', models.IntegerField()),
                ('Volume', models.IntegerField()),
                ('Rate_Per_Slab', models.IntegerField()),
                ('Total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Desk_Planning_Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Packs_Slabs', models.CharField(max_length=15)),
                ('Max_Slab', models.IntegerField()),
                ('Rate', models.IntegerField()),
                ('Total_Quantity', models.IntegerField()),
                ('Volume', models.IntegerField()),
                ('Rate_Per_Slab', models.IntegerField()),
                ('Total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Desk_Utilization_Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Packs_Slabs', models.CharField(max_length=15)),
                ('Max_Slab', models.IntegerField()),
                ('Rate', models.IntegerField()),
                ('Total_Quantity', models.IntegerField()),
                ('Volume', models.IntegerField()),
                ('Rate_Per_Slab', models.IntegerField()),
                ('Total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee_One_Mobile_App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Packs_Slabs', models.CharField(max_length=15)),
                ('Max_Slab', models.IntegerField()),
                ('Rate', models.IntegerField()),
                ('Total_Quantity', models.IntegerField()),
                ('Volume', models.IntegerField()),
                ('Rate_Per_Slab', models.IntegerField()),
                ('Total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Packs_Slabs', models.CharField(max_length=15)),
                ('Max_Slab', models.IntegerField()),
                ('Rate', models.IntegerField()),
                ('Total_Quantity', models.IntegerField()),
                ('Volume', models.IntegerField()),
                ('Rate_Per_Slab', models.IntegerField()),
                ('Total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Human_body_temperature_License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Packs_Slabs', models.CharField(max_length=15)),
                ('Max_Slab', models.IntegerField()),
                ('Rate', models.IntegerField()),
                ('Total_Quantity', models.IntegerField()),
                ('Volume', models.IntegerField()),
                ('Rate_Per_Slab', models.IntegerField()),
                ('Total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Kiosk_License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Packs_Slabs', models.CharField(max_length=15)),
                ('Max_Slab', models.IntegerField()),
                ('Rate', models.IntegerField()),
                ('Total_Quantity', models.IntegerField()),
                ('Volume', models.IntegerField()),
                ('Rate_Per_Slab', models.IntegerField()),
                ('Total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Meeting_Room_License_Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Packs_Slabs', models.CharField(max_length=15)),
                ('Max_Slab', models.IntegerField()),
                ('Rate', models.IntegerField()),
                ('Total_Quantity', models.IntegerField()),
                ('Volume', models.IntegerField()),
                ('Rate_Per_Slab', models.IntegerField()),
                ('Total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Meeting_Room_License_Occupancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Packs_Slabs', models.CharField(max_length=15)),
                ('Max_Slab', models.IntegerField()),
                ('Rate', models.IntegerField()),
                ('Total_Quantity', models.IntegerField()),
                ('Volume', models.IntegerField()),
                ('Rate_Per_Slab', models.IntegerField()),
                ('Total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Meeting_Room_License_People_Count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Packs_Slabs', models.CharField(max_length=15)),
                ('Max_Slab', models.IntegerField()),
                ('Rate', models.IntegerField()),
                ('Total_Quantity', models.IntegerField()),
                ('Volume', models.IntegerField()),
                ('Rate_Per_Slab', models.IntegerField()),
                ('Total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Restroom_License_Odour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Packs_Slabs', models.CharField(max_length=15)),
                ('Max_Slab', models.IntegerField()),
                ('Rate', models.IntegerField()),
                ('Total_Quantity', models.IntegerField()),
                ('Volume', models.IntegerField()),
                ('Rate_Per_Slab', models.IntegerField()),
                ('Total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Restroom_License_People_Count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Packs_Slabs', models.CharField(max_length=15)),
                ('Max_Slab', models.IntegerField()),
                ('Rate', models.IntegerField()),
                ('Total_Quantity', models.IntegerField()),
                ('Volume', models.IntegerField()),
                ('Rate_Per_Slab', models.IntegerField()),
                ('Total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Restroom_License_Wet_floor_detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Packs_Slabs', models.CharField(max_length=15)),
                ('Max_Slab', models.IntegerField()),
                ('Rate', models.IntegerField()),
                ('Total_Quantity', models.IntegerField()),
                ('Volume', models.IntegerField()),
                ('Rate_Per_Slab', models.IntegerField()),
                ('Total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rostering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Packs_Slabs', models.CharField(max_length=15)),
                ('Max_Slab', models.IntegerField()),
                ('Rate', models.IntegerField()),
                ('Total_Quantity', models.IntegerField()),
                ('Volume', models.IntegerField()),
                ('Rate_Per_Slab', models.IntegerField()),
                ('Total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Wayfinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Packs_Slabs', models.CharField(max_length=15)),
                ('Max_Slab', models.IntegerField()),
                ('Rate', models.IntegerField()),
                ('Total_Quantity', models.IntegerField()),
                ('Volume', models.IntegerField()),
                ('Rate_Per_Slab', models.IntegerField()),
                ('Total', models.IntegerField()),
            ],
        ),
    ]
