# Generated by Django 4.0.4 on 2022-05-31 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin1', '0013_desk_booking_solution_desk_planning_solution_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desk_booking_solution',
            name='id',
        ),
        migrations.AddField(
            model_name='desk_booking_solution',
            name='sr_no',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
