# Generated by Django 4.0.4 on 2022-08-30 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin1', '0014_quotation_active_quotation_bms_cabling_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotation',
            old_name='Active',
            new_name='_Active',
        ),
        migrations.RenameField(
            model_name='quotation',
            old_name='Bms_Cabling',
            new_name='_Bms_Cabling',
        ),
        migrations.RenameField(
            model_name='quotation',
            old_name='Bms_Piping',
            new_name='_Bms_Piping',
        ),
        migrations.RenameField(
            model_name='quotation',
            old_name='Bms_Sensors',
            new_name='_Bms_Sensors',
        ),
        migrations.RenameField(
            model_name='quotation',
            old_name='Bms_Trays',
            new_name='_Bms_Trays',
        ),
        migrations.RenameField(
            model_name='quotation',
            old_name='Ddc',
            new_name='_Ddc',
        ),
        migrations.RenameField(
            model_name='quotation',
            old_name='Ethernet',
            new_name='_Ethernet',
        ),
        migrations.RenameField(
            model_name='quotation',
            old_name='Fiber',
            new_name='_Fiber',
        ),
        migrations.RenameField(
            model_name='quotation',
            old_name='General',
            new_name='_General',
        ),
        migrations.RenameField(
            model_name='quotation',
            old_name='Others',
            new_name='_Others',
        ),
        migrations.RenameField(
            model_name='quotation',
            old_name='Soft_Items',
            new_name='_Soft_Items',
        ),
        migrations.RenameField(
            model_name='quotation',
            old_name='Third_Party',
            new_name='_Third_Party',
        ),
    ]
