# Generated by Django 4.0.4 on 2022-06-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin1', '0015_remove_desk_planning_solution_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spaziopricecalculator',
            name='COM',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='spaziopricecalculator',
            name='Rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='spaziopricecalculator',
            name='SubTotal',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='spaziopricecalculator',
            name='Total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='spaziopricecalculator',
            name='TotalAmountwithInsurance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='spaziopricecalculator',
            name='TotalwithWarranty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='spaziopricecalculator',
            name='Warranty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='spaziopricecalculator',
            name='Year2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='spaziopricecalculator',
            name='Year3',
            field=models.IntegerField(default=0),
        ),
    ]
