# Generated by Django 4.0.4 on 2022-09-01 17:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin1', '0015_rename_active_quotation__active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotation',
            old_name='_General',
            new_name='_Efforts',
        ),
        migrations.AlterField(
            model_name='quotation',
            name='date',
            field=models.DateField(default=datetime.date(2022, 9, 1)),
        ),
    ]
