# Generated by Django 4.0.4 on 2022-06-09 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin1', '0016_alter_spaziopricecalculator_com_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Automate_Pricing',
            fields=[
                ('sr_no', models.AutoField(primary_key=True, serialize=False)),
                ('Model_No', models.CharField(max_length=50)),
                ('Max_Slab', models.IntegerField()),
                ('Pack_Desc', models.CharField(max_length=50)),
                ('Inr_Basic', models.IntegerField()),
                ('Inr_Basic_Per_Kpi', models.IntegerField()),
                ('Inr_Premium', models.IntegerField()),
                ('Inr_Premium_Per_Kpi', models.IntegerField()),
                ('Usd_Basic', models.IntegerField()),
                ('Usd_Premium', models.IntegerField()),
            ],
        ),
    ]
