# Generated by Django 4.0.4 on 2022-09-01 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin1', '0016_rename__general_quotation__efforts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='_Soft_Items',
        ),
    ]
