# Generated by Django 4.0.4 on 2022-06-09 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin1', '0017_automate_pricing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Software_Revised_Extra',
            fields=[
                ('sr_no', models.AutoField(primary_key=True, serialize=False)),
                ('Key', models.IntegerField()),
                ('Value', models.IntegerField()),
                ('Info', models.CharField(max_length=100)),
            ],
        ),
    ]
