# Generated by Django 4.0.4 on 2022-09-05 13:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin1', '0019_alter_quotation__active_alter_quotation__bms_cabling_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discription', models.CharField(default='', max_length=200)),
                ('minslab', models.IntegerField(default=0)),
                ('maxslab', models.IntegerField(default=0)),
                ('brate', models.IntegerField(default=0)),
                ('prate', models.IntegerField(default=0)),
                ('btotal', models.IntegerField(default=0)),
                ('ptotal', models.IntegerField(default=0)),
                ('platform', models.IntegerField(default=0)),
                ('perpoint', models.IntegerField(default=0)),
                ('basiccharges', models.IntegerField(default=0)),
                ('discountpercent', models.IntegerField(default=0)),
                ('discountrate', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='quotation',
            name='date',
            field=models.DateField(default=datetime.date(2022, 9, 5)),
        ),
    ]
