# Generated by Django 4.0.4 on 2022-06-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin1', '0019_alter_software_revised_extra_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software_revised_extra',
            name='Info',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
