# Generated by Django 4.0.4 on 2022-09-15 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin1', '0020_iaq_alter_quotation_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pm_After_Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minslab', models.IntegerField(default=0)),
                ('maxslab', models.IntegerField(default=0)),
                ('rate', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Pm_After_Margin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minslab', models.IntegerField(default=0)),
                ('maxslab', models.IntegerField(default=0)),
                ('rate', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Pm_Final',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minslab', models.IntegerField(default=0)),
                ('maxslab', models.IntegerField(default=0)),
                ('rate', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='quotation',
            name='date',
            field=models.DateField(default=datetime.date(2022, 9, 15)),
        ),
    ]
