# Generated by Django 4.0.4 on 2022-06-09 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin1', '0020_alter_software_revised_extra_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software_revised_extra',
            name='Value',
            field=models.FloatField(),
        ),
    ]
