# Generated by Django 4.0.4 on 2022-06-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin1', '0021_alter_software_revised_extra_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='IandC',
            fields=[
                ('sr_no', models.AutoField(primary_key=True, serialize=False)),
                ('Deployment_Activity', models.CharField(max_length=200)),
                ('Resource_Level', models.CharField(max_length=100)),
                ('Common_Efforts_in_Man_Day', models.IntegerField()),
                ('Spazio_Software_Efforts_in_Man_Day', models.IntegerField()),
                ('Meeting_Room_Booking_Efforts_in_Man_Day', models.IntegerField()),
                ('Meeting_Room_People_count_occupancy_Efforts_in_Man_Day', models.IntegerField()),
                ('Restroom_Hygiene_Efforts_in_Man_Day', models.IntegerField()),
                ('IAQ_Automate_Efforts_in_Man_Day', models.IntegerField()),
                ('Wayfinding_Efforts_in_Man_Day', models.IntegerField()),
                ('Feedback_Efforts_in_Man_Day', models.IntegerField()),
            ],
        ),
    ]
