# Generated by Django 4.0.4 on 2022-09-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin1', '0021_pm_after_cost_pm_after_margin_pm_final_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pm_after_cost',
            name='sr_no',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pm_after_margin',
            name='sr_no',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pm_final',
            name='sr_no',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
