# Generated by Django 4.0.4 on 2022-09-22 10:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin1', '0022_pm_after_cost_sr_no_pm_after_margin_sr_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='date',
            field=models.DateField(default=datetime.date(2022, 9, 22)),
        ),
    ]
