# Generated by Django 4.0.4 on 2022-06-10 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin1', '0022_iandc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iandc',
            old_name='Common_Efforts_in_Man_Day',
            new_name='Common',
        ),
        migrations.RenameField(
            model_name='iandc',
            old_name='Feedback_Efforts_in_Man_Day',
            new_name='Feedback',
        ),
        migrations.RenameField(
            model_name='iandc',
            old_name='IAQ_Automate_Efforts_in_Man_Day',
            new_name='IAQ_Automate',
        ),
        migrations.RenameField(
            model_name='iandc',
            old_name='Meeting_Room_Booking_Efforts_in_Man_Day',
            new_name='Meeting_Room_Booking',
        ),
        migrations.RenameField(
            model_name='iandc',
            old_name='Meeting_Room_People_count_occupancy_Efforts_in_Man_Day',
            new_name='Meeting_Room_People_count_occupancy',
        ),
        migrations.RenameField(
            model_name='iandc',
            old_name='Restroom_Hygiene_Efforts_in_Man_Day',
            new_name='Restroom_Hygiene',
        ),
        migrations.RenameField(
            model_name='iandc',
            old_name='Spazio_Software_Efforts_in_Man_Day',
            new_name='Spazio_Software',
        ),
        migrations.RenameField(
            model_name='iandc',
            old_name='Wayfinding_Efforts_in_Man_Day',
            new_name='Wayfinding',
        ),
    ]
