# Generated by Django 4.0.4 on 2022-06-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin1', '0023_rename_common_efforts_in_man_day_iandc_common_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iandc',
            name='Common',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='iandc',
            name='Feedback',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='iandc',
            name='IAQ_Automate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='iandc',
            name='Meeting_Room_Booking',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='iandc',
            name='Meeting_Room_People_count_occupancy',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='iandc',
            name='Restroom_Hygiene',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='iandc',
            name='Spazio_Software',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='iandc',
            name='Wayfinding',
            field=models.IntegerField(default=0),
        ),
    ]
