# Generated by Django 4.0.4 on 2022-06-14 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin1', '0025_alter_iandc_deployment_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='automate_pricing',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='desk_booking_solution',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='desk_planning_solution',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='desk_utilization_solution',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee_one_mobile_app',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='human_body_temperature_license',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iandc',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kiosk_license',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meeting_room_license_booking',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meeting_room_license_occupancy',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meeting_room_license_people_count',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restroom_license_odour',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restroom_license_people_count',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restroom_license_wet_floor_detection',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rostering',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='software_revised_extra',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wayfinding',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='automate_pricing',
            name='sr_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='desk_booking_solution',
            name='sr_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='desk_planning_solution',
            name='sr_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='desk_utilization_solution',
            name='sr_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employee_one_mobile_app',
            name='sr_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='sr_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='human_body_temperature_license',
            name='sr_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='iandc',
            name='sr_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='kiosk_license',
            name='sr_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='meeting_room_license_booking',
            name='sr_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='meeting_room_license_occupancy',
            name='sr_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='meeting_room_license_people_count',
            name='sr_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='restroom_license_odour',
            name='sr_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='restroom_license_people_count',
            name='sr_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='restroom_license_wet_floor_detection',
            name='sr_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rostering',
            name='sr_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='software_revised_extra',
            name='sr_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='wayfinding',
            name='sr_no',
            field=models.IntegerField(),
        ),
    ]
