# Generated by Django 4.0.4 on 2022-06-14 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin1', '0026_automate_pricing_id_desk_booking_solution_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automate_pricing',
            name='id',
        ),
        migrations.AlterField(
            model_name='automate_pricing',
            name='sr_no',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
