# Generated by Django 4.0.4 on 2022-06-15 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin1', '0003_automate_pricing_desk_booking_solution_and_more'),
        ('Admin1', '0027_remove_automate_pricing_id_and_more'),
    ]

    operations = [
    ]
